name: Safe-Trip-CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.12.0 ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Set Yarn Version
        id: set-version
        run: |
          yarn set version 4.1.0
          echo "YARN_VERSION=$(yarn -v)" >> $GITHUB_OUTPUT

      - name: Yarn Cache - PnP
        uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            .pnp.*
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ steps.set-version.outputs.YARN_VERSION }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-      

      #      - name: Generate Environment Variables File for Production
      #        env:
      #          REACT_APP_WEBSOCKET_URL: ${{ secrets.REACT_APP_WEBSOCKET_URL }}
      #          APP_PUBLIC_URL: ${{ secrets.APP_PUBLIC_URL }}
      #        run: |
      #          echo "REACT_APP_WEBSOCKET_URL=$REACT_APP_WEBSOCKET_URL" >> .env
      #          echo "REACT_APP_API_URL=$APP_PUBLIC_URL" >> .env

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Check Eslint, Prettier, Stylelint
        run: yarn lint-staged

      - name: Build Packages
        run: yarn build
